services:
  pinnlabs_website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinnlabs_website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - COMPOSE_BAKE=true
      - PORT=5000
    ports:
      - "5000:5000"
